### ISSUE TITLE
Question on conformer numbers

### ISSUE THREAD

**Issue by acharkq** [GRAPH-0/JODO#3]
Hi Authors,

Congrats on the great work!

As I was reading your paper, I found that you retain one conformer with the lowest energy and discarded other conformers. This is a different experimental setting as compared to EDM. This processing also reduces the dataset size from 6million to 200k. May I know the effect of this operation? Why is it necessary? And does it positively or negatively influence performance?

Thanks!

**Comment by GRAPH-0** [comment]
Thank you for your interest！
If you feel necessary, you are free to train the model on the full GEOM-Drug. I only keep one conformation mainly for faster validation of the model's ability of distribution modeling.
Actually, the EDM I retrained on 200k data showed a similar performance to the original version.

**Comment by acharkq** [comment]
Thanks for the answer!
