### ISSUE TITLE
Other dataset apply

### ISSUE THREAD

**Issue by yddr** [GRAPH-0/JODO#4]
Hi, Thanks for releasing awesome code!

I want to apply to other dataset not QM9, GEOM, and so on.
I converted smiles dataset to .sdf file.
But I'm confused the [**our processed dataset files**](https://github.com/GRAPH-0/JODO/blob/main/README.md) you mentioned in readme.md file.

Well, **your preprocess method** is datasets/build_data.py from what I understand, right?
And can I use the other dataset, if use the build_dataset.py?

I'll really appreciate for your reply.

**Comment by GRAPH-0** [comment]
Unfortunately, we do not currently offer support for applying to other datasets.  But I may help you implement your dataset within our framework. This mainly involves creating a new `XX_dataset.py` and modifying the related contents of `build_dataset.py` and `datasets_config.py`.
If you need to generate 2D graphs, please refer to the `zinc_dataset.py` file. On the other hand, if you need to generate 3D geometric graphs, you can refer to the `qm9_dataset.py` file for implementation. 
In fact, the preprocessing files we provide are mainly implemented by the `process()` function in `InMemoryDataset`, except for Geom.

**Comment by yddr** [comment]
I'll try implement with referencing your reply and files.

Thanks for the quick and kind reply.
