### ISSUE TITLE
QM9 FCD metrics

### ISSUE THREAD

**Issue by DWF09** [GRAPH-0/JODO#8]
Hi, I would like to ask how the FCD metrics were obtained in the QM9 dataset in your paper? Is it case 1 below or case 2 or something else?

CUDA_VISIBLE_DEVICES=0 python main.py --config configs/vpsde_qm9_uncond_jodo.py --mode train --workdir exp_uncond/vpsde_qm9_jodo

1. In the result of running the above command you get
2. After running the above command, the molecules are regenerated with the obtained model and evaluated again to get

**Comment by GRAPH-0** [comment]
Case 2, using sampling pipeline.
Please check `eval_rdkit_pkl.py` if you have already generated molecules.

**Comment by DWF09** [comment]
Thanks

**Comment by DWF09** [comment]
CUDA_VISIBLE_DEVICES=0 python main.py --config configs/vpsde_qm9_uncond_jodo.py --mode train --workdir exp_uncond/vpsde_qm9_jodo

Hi, I've currently finished training using the above instructions, and I'd like to ask you, if I want to get the QM9 metrics from your paper, is the next step to run the following two instructions in sequence? Are there any other instructions that need to be run?

1.CUDA_VISIBLE_DEVICES=2 python main.py --config configs/vpsde_qm9_uncond_jodo.py ---mode eval --workdir exp_uncond/vpsde_qm9_jodo --config. eval.ckpts '30' --config.eval.batch_size 2500 --config.sampling.steps 1000
2.python eval_rdkit_pkl.py --dataset_name qm9 --type both --sub_geometry=True --root_path YOUR_DATASET_PATH --pkl_path YOUR_MOL_PATH

**Comment by GRAPH-0** [comment]
Please use the first command to generate molecules and evaluate them. You can set the `workdir` and `config.eval.ckpts` according to your needs.

**Comment by DWF09** [comment]
Are the QM9 metrics in your paper derived from the first command? Did you change --workdir or --config?

**Comment by GRAPH-0** [comment]
`workdir`: the path where you save the checkpoint.
`config.eval.ckpts`: the serial number of checkpoint to evaluate.
