### ISSUE TITLE
Consultation on model results

### ISSUE THREAD

**Issue by DWF09** [GRAPH-0/JODO#9]
Hi, you mentioned in your paper that your results were averaged using your trained model sampled three separate times, meaning that you repeated the following code three times to get three results and then averaged them?

CUDA_VISIBLE_DEVICES=2 python main.py --config configs/vpsde_qm9_uncond_jodo.py --mode eval --workdir exp_uncond/vpsde_qm9_jodo --config.eval.ckpts '30' --config.eval.batch_size 2500 --config.sampling.steps 1000

**Comment by GRAPH-0** [comment]
Please use different seeds by setting `--config.seed`

**Comment by DWF09** [comment]
What are the three --config.seed values you chose?

**Comment by GRAPH-0** [comment]
Using random seeds you can obtain similar results.

**Comment by DWF09** [comment]
Okay. Thank you.
